
import { Language } from './types';

export const LANGUAGES: Language[] = ['English', 'Spanish', 'French', 'German', 'Japanese', 'Chinese'];

type UITex = {
    [key: string]: { [lang in Language]: string };
};

export const UI_TEXT: UITex = {
    analyzeScript: {
        English: 'Analyze Script',
        Spanish: 'Analizar Guión',
        French: 'Analyser le Scénario',
        German: 'Skript Analysieren',
        Japanese: '脚本を分析する',
        Chinese: '分析脚本',
    },
    pasteScript: {
        English: 'Paste your film script here...',
        Spanish: 'Pega tu guión aquí...',
        French: 'Collez votre scénario ici...',
        German: 'Fügen Sie hier Ihr Filmskript ein...',
        Japanese: 'ここに脚本を貼り付けてください...',
        Chinese: '在此处粘贴您的电影剧本...',
    },
    language: {
        English: 'Language',
        Spanish: 'Idioma',
        French: 'Langue',
        German: 'Sprache',
        Japanese: '言語',
        Chinese: '语言',
    },
    dashboard: {
        English: 'Dashboard',
        Spanish: 'Panel',
        French: 'Tableau de Bord',
        German: 'Dashboard',
        Japanese: 'ダッシュボード',
        Chinese: '仪表板',
    },
    sceneBreakdown: {
        English: 'Scene Breakdown',
        Spanish: 'Desglose de Escenas',
        French: 'Découpage Technique',
        German: 'Szenenaufschlüsselung',
        Japanese: 'シーンの内訳',
        Chinese: '场景分解',
    },
    scheduler: {
        English: 'Scheduler',
        Spanish: 'Planificador',
        French: 'Planificateur',
        German: 'Planer',
        Japanese: 'スケジューラ',
        Chinese: '调度器',
    },
    storyboard: {
        English: 'Storyboard',
        Spanish: 'Storyboard',
        French: 'Storyboard',
        German: 'Storyboard',
        Japanese: 'ストーリーボード',
        Chinese: '故事板',
    },
    productionGuide: {
        English: 'Production Guide',
        Spanish: 'Guía de Producción',
        French: 'Guide de Production',
        German: 'Produktionsleitfaden',
        Japanese: '制作ガイド',
        Chinese: '制作指南',
    },
    continuity: {
        English: 'Continuity',
        Spanish: 'Continuidad',
        French: 'Continuité',
        German: 'Kontinuität',
        Japanese: '連続性',
        Chinese: '连续性',
    },
    generateSchedule: {
        English: 'Generate Shooting Schedule',
        Spanish: 'Generar Plan de Rodaje',
        French: 'Générer le Plan de Tournage',
        German: 'Drehplan Erstellen',
        Japanese: '撮影スケジュールを作成',
        Chinese: '生成拍摄时间表',
    },
    generateStoryboard: {
        English: 'Generate Storyboard',
        Spanish: 'Generar Storyboard',
        French: 'Générer le Storyboard',
        German: 'Storyboard Erstellen',
        Japanese: 'ストーリーボードを作成',
        Chinese: '生成故事板',
    },
    generateGuide: {
        English: 'Generate Production Guide',
        Spanish: 'Generar Guía de Producción',
        French: 'Générer le Guide de Production',
        German: 'Produktionsleitfaden Erstellen',
        Japanese: '制作ガイドを生成',
        Chinese: '生成制作指南',
    },
    generateContinuityReport: {
        English: 'Generate Continuity Report',
        Spanish: 'Generar Informe de Continuidad',
        French: 'Générer le Rapport de Continuité',
        German: 'Kontinuitätsbericht Erstellen',
        Japanese: '連続性レポートを生成',
        Chinese: '生成连续性报告',
    },
     selectScene: {
        English: 'Select a scene to generate its storyboard',
        Spanish: 'Selecciona una escena para generar su storyboard',
        French: 'Sélectionnez une scène pour générer son storyboard',
        German: 'Wähle eine Szene aus, um das Storyboard zu erstellen',
        Japanese: 'シーンを選択してストーリーボードを生成します',
        Chinese: '选择一个场景以生成其故事板',
    },
    downloadPdf: {
        English: 'Download PDF',
        Spanish: 'Descargar PDF',
        French: 'Télécharger le PDF',
        German: 'PDF Herunterladen',
        Japanese: 'PDFをダウンロード',
        Chinese: '下载PDF',
    },
    cameraLenses: {
        English: 'Camera & Lenses',
        Spanish: 'Cámara y Lentes',
        French: 'Caméra et Objectifs',
        German: 'Kamera & Objektive',
        Japanese: 'カメラ＆レンズ',
        Chinese: '相机与镜头',
    },
    artDepartment: {
        English: 'Art Department',
        Spanish: 'Departamento de Arte',
        French: "Département Artistique",
        German: 'Szenenbild',
        Japanese: '美術部',
        Chinese: '美术部门',
    },
    lighting: {
        English: 'Lighting',
        Spanish: 'Iluminación',
        French: 'Éclairage',
        German: 'Beleuchtung',
        Japanese: '照明',
        Chinese: '灯光',
    },
    costumes: {
        English: 'Costumes',
        Spanish: 'Vestuario',
        French: 'Costumes',
        German: 'Kostüme',
        Japanese: '衣装',
        Chinese: '服装',
    },
};
